(RE-15420) Add puppet8-release files.
puppetlabs/puppetlabs-release pull request #290
Opened 2023-04-14 17:42 UTC by isaac-hammes

2023-04-17 17:18 UTC, e-gris requested changes

2023-04-17 17:18 UTC, e-gris commented on source/yum.puppetlabs.com/puppet8-release.repo.template
> +       file:///etc/pki/rpm-gpg/RPM-GPG-KEY-puppet8-release
The old release key isn't needed anymore; it should be deleted here.

2023-04-19 17:22 UTC, isaac-hammes commented on source/yum.puppetlabs.com/puppet8-release.repo.template
> +       file:///etc/pki/rpm-gpg/RPM-GPG-KEY-puppet8-release
Ok. Thank you. I'll get that fixed.

2023-04-19 18:04 UTC, e-gris approved these changes

2023-04-19 18:06 UTC, merged